/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calcula_Cientifica;

import java.awt.event.KeyEvent;

/**
 *
 * @author vinicius
 */
public class Calculadora_C extends javax.swing.JFrame {
    double primeiroNum;
    double segundoNum;
    double resultado;
    String operacoes;
    private Object math;
    /**
     * Creates new form Calculadora_C
     */
    public Calculadora_C() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtDisplay = new javax.swing.JTextField();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtnDividir = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtnVezes = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnPonto = new javax.swing.JButton();
        jbtnMenos = new javax.swing.JButton();
        jbtnresultado = new javax.swing.JButton();
        jbtnMaisMenos = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jbtnRaiz = new javax.swing.JButton();
        jbtnBackspace = new javax.swing.JButton();
        jbtnMais = new javax.swing.JButton();
        jbtnLog = new javax.swing.JButton();
        jbtnSen = new javax.swing.JButton();
        jbtnPi = new javax.swing.JButton();
        jbtnCos = new javax.swing.JButton();
        jbtnXY = new javax.swing.JButton();
        jbtnTan = new javax.swing.JButton();
        jbtnX2 = new javax.swing.JButton();
        jbtnEuler = new javax.swing.JButton();
        jbtnX3 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTxtDisplay.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jTxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtDisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtDisplayKeyTyped(evt);
            }
        });

        jbtn8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtn8.setText("8");
        jbtn8.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtn8.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtn8.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });

        jbtn9.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtn9.setText("9");
        jbtn9.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtn9.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtn9.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });

        jbtn7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtn7.setText("7");
        jbtn7.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtn7.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtn7.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });

        jbtn4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtn4.setText("4");
        jbtn4.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtn4.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtn4.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });

        jbtn5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtn5.setText("5");
        jbtn5.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtn5.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtn5.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });

        jbtn6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtn6.setText("6");
        jbtn6.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtn6.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtn6.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });

        jbtnDividir.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtnDividir.setText("÷");
        jbtnDividir.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtnDividir.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtnDividir.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDividirActionPerformed(evt);
            }
        });

        jbtn1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtn1.setText("1");
        jbtn1.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtn1.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtn1.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });

        jbtn2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtn2.setText("2");
        jbtn2.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtn2.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtn2.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });

        jbtn3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtn3.setText("3");
        jbtn3.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtn3.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtn3.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });

        jbtnVezes.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtnVezes.setText("×");
        jbtnVezes.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtnVezes.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtnVezes.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtnVezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVezesActionPerformed(evt);
            }
        });

        jbtn0.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtn0.setText("0");
        jbtn0.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtn0.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtn0.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });

        jbtnPonto.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtnPonto.setText(".");
        jbtnPonto.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtnPonto.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtnPonto.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtnPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPontoActionPerformed(evt);
            }
        });

        jbtnMenos.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtnMenos.setText("−");
        jbtnMenos.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtnMenos.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtnMenos.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenosActionPerformed(evt);
            }
        });

        jbtnresultado.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtnresultado.setText("=");
        jbtnresultado.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtnresultado.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtnresultado.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtnresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnresultadoActionPerformed(evt);
            }
        });

        jbtnMaisMenos.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtnMaisMenos.setText("±");
        jbtnMaisMenos.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtnMaisMenos.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtnMaisMenos.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtnMaisMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMaisMenosActionPerformed(evt);
            }
        });

        jbtnClear.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtnClear.setText("C");
        jbtnClear.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtnClear.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtnClear.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });

        jbtnRaiz.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtnRaiz.setText("√");
        jbtnRaiz.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtnRaiz.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtnRaiz.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRaizActionPerformed(evt);
            }
        });

        jbtnBackspace.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jbtnBackspace.setText("⌫");
        jbtnBackspace.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtnBackspace.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtnBackspace.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackspaceActionPerformed(evt);
            }
        });

        jbtnMais.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtnMais.setText("+");
        jbtnMais.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtnMais.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtnMais.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtnMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMaisActionPerformed(evt);
            }
        });

        jbtnLog.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtnLog.setText("Log");
        jbtnLog.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtnLog.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtnLog.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogActionPerformed(evt);
            }
        });

        jbtnSen.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtnSen.setText("Sen");
        jbtnSen.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtnSen.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtnSen.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtnSen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSenActionPerformed(evt);
            }
        });

        jbtnPi.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jbtnPi.setText("π");
        jbtnPi.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtnPi.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtnPi.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtnPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPiActionPerformed(evt);
            }
        });

        jbtnCos.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtnCos.setText("Cos");
        jbtnCos.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtnCos.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtnCos.setPreferredSize(new java.awt.Dimension(70, 30));

        jbtnXY.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtnXY.setText("x^y");
        jbtnXY.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtnXY.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtnXY.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtnXY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXYActionPerformed(evt);
            }
        });

        jbtnTan.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtnTan.setText("Tan");
        jbtnTan.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtnTan.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtnTan.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTanActionPerformed(evt);
            }
        });

        jbtnX2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtnX2.setText("x^2");
        jbtnX2.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtnX2.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtnX2.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtnX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnX2ActionPerformed(evt);
            }
        });

        jbtnEuler.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jbtnEuler.setText("e");
        jbtnEuler.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtnEuler.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtnEuler.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtnEuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEulerActionPerformed(evt);
            }
        });

        jbtnX3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jbtnX3.setText("x^3");
        jbtnX3.setMaximumSize(new java.awt.Dimension(70, 30));
        jbtnX3.setMinimumSize(new java.awt.Dimension(70, 30));
        jbtnX3.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtnX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnX3ActionPerformed(evt);
            }
        });

        jButton29.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton29.setText("+");
        jButton29.setMaximumSize(new java.awt.Dimension(70, 30));
        jButton29.setMinimumSize(new java.awt.Dimension(70, 30));
        jButton29.setPreferredSize(new java.awt.Dimension(70, 30));

        jMenu1.setText("Arquivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Padrao");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cientifica");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnXY, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtnPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnMaisMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtnresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtnX2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnEuler, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtnX3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnMais, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTxtDisplay))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnSen, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnMais, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnSen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnXY, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnX2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnEuler, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnMaisMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnX3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setResizable(true);
        this.setSize(400, 457);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setResizable(true);
        this.setSize(400, 457);
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setResizable(true);
        this.setSize(606, 457);
        jTxtDisplay.setSize(600, 30);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jbtnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackspaceActionPerformed
        String bsp = null;
        
        if(jTxtDisplay.getText().length() > 0){
            StringBuilder strB = new StringBuilder(jTxtDisplay.getText());
            strB.deleteCharAt(jTxtDisplay.getText().length() -1);
            bsp = strB.toString();
            jTxtDisplay.setText(bsp);
        }
    }//GEN-LAST:event_jbtnBackspaceActionPerformed

    private void jbtnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenosActionPerformed
        primeiroNum = Double.parseDouble(jTxtDisplay.getText());
        jTxtDisplay.setText(null);
        operacoes=("-");
    }//GEN-LAST:event_jbtnMenosActionPerformed

    private void jbtnVezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVezesActionPerformed
        primeiroNum = Double.parseDouble(jTxtDisplay.getText());
        jTxtDisplay.setText(null);
        operacoes=("*");
    }//GEN-LAST:event_jbtnVezesActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        // TODO add your handling code here:
        String iNum = jTxtDisplay.getText() + jbtn7.getText();
        jTxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        // TODO add your handling code here:
        String iNum = jTxtDisplay.getText() + jbtn8.getText();
        jTxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        // TODO add your handling code here:
        String iNum = jTxtDisplay.getText() + jbtn9.getText();
        jTxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        // TODO add your handling code here:
                String iNum = jTxtDisplay.getText() + jbtn4.getText();
        jTxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        // TODO add your handling code here:
        String iNum = jTxtDisplay.getText() + jbtn5.getText();
        jTxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        // TODO add your handling code here:
        String iNum = jTxtDisplay.getText() + jbtn6.getText();
        jTxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        // TODO add your handling code here:
        String iNum = jTxtDisplay.getText() + jbtn1.getText();
        jTxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        // TODO add your handling code here:
        String iNum = jTxtDisplay.getText() + jbtn2.getText();
        jTxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        // TODO add your handling code here:
        String iNum = jTxtDisplay.getText() + jbtn3.getText();
        jTxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        // TODO add your handling code here:
        String iNum = jTxtDisplay.getText() + jbtn0.getText();
        jTxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        // TODO add your handling code here:
        jTxtDisplay.setText("");
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtnPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPontoActionPerformed
        if(!jTxtDisplay.getText().contains(",")){
            jTxtDisplay.setText(jTxtDisplay.getText() + jbtnPonto.getText());
        }
    }//GEN-LAST:event_jbtnPontoActionPerformed

    private void jbtnMaisMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMaisMenosActionPerformed
        // TODO add your handling code here:
        double op = Double.parseDouble(String.valueOf(jTxtDisplay.getText()));
        op = op *(-1);
        jTxtDisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jbtnMaisMenosActionPerformed

    private void jbtnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRaizActionPerformed
        // TODO add your handling code here:
        double op = Double.parseDouble(String.valueOf(jTxtDisplay.getText()));
        op = Math.sqrt(op);
        jTxtDisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jbtnRaizActionPerformed

    private void jbtnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogActionPerformed
        // TODO add your handling code here:
        double op = Double.parseDouble(String.valueOf(jTxtDisplay.getText()));
        op = Math.log(op);
        jTxtDisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jbtnLogActionPerformed

    private void jbtnSenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSenActionPerformed
        // TODO add your handling code here:
        double op = Double.parseDouble(String.valueOf(jTxtDisplay.getText()));
        op = Math.sin(op);
        jTxtDisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jbtnSenActionPerformed

    private void jbtnPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPiActionPerformed
        // TODO add your handling code here:
        double op;
        op = (3.14159265359);
        jTxtDisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jbtnPiActionPerformed

    private void jbtnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTanActionPerformed
        double op = Double.parseDouble(String.valueOf(jTxtDisplay.getText()));
        op = Math.tan(op);
        jTxtDisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jbtnTanActionPerformed

    private void jbtnXYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXYActionPerformed
        // TODO add your handling code here:
        double op = Double.parseDouble(String.valueOf(jTxtDisplay.getText()));
        op = Math.pow(op, op);
        jTxtDisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jbtnXYActionPerformed

    private void jbtnX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnX2ActionPerformed
        // TODO add your handling code here:
        double op = Double.parseDouble(String.valueOf(jTxtDisplay.getText()));
        op = (op * op);
        jTxtDisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jbtnX2ActionPerformed

    private void jbtnX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnX3ActionPerformed
        // TODO add your handling code here:
        double op = Double.parseDouble(String.valueOf(jTxtDisplay.getText()));
        op = (op * op * op);
        jTxtDisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jbtnX3ActionPerformed

    private void jbtnEulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEulerActionPerformed
        double op;
        op = (2.71828);
        jTxtDisplay.setText(String.valueOf(op));
    }//GEN-LAST:event_jbtnEulerActionPerformed

    private void jTxtDisplayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtDisplayKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||(c == KeyEvent.VK_DELETE)){
            getToolkit().beep();
        evt.consume();
        
    }
    }//GEN-LAST:event_jTxtDisplayKeyTyped

    private void jbtnresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnresultadoActionPerformed
        String resposta;
        segundoNum = Double.parseDouble(jTxtDisplay.getText());
        if (operacoes == "+"){
            resultado = primeiroNum + segundoNum;
            resposta = String.format("%.2f", resultado);
            jTxtDisplay.setText(resposta);
        }
        else if (operacoes == "-"){
            resultado = primeiroNum - segundoNum;
            resposta = String.format("%.2f", resultado);
            jTxtDisplay.setText(resposta);
        }
        else if (operacoes == "*"){
            resultado = primeiroNum * segundoNum;
            resposta = String.format("%.2f", resultado);
            jTxtDisplay.setText(resposta);
        }
        else if (operacoes == "÷"){
            resultado = primeiroNum / segundoNum;
            resposta = String.format("%.2f", resultado);
            jTxtDisplay.setText(resposta);
        }
        
    }//GEN-LAST:event_jbtnresultadoActionPerformed

    private void jbtnMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMaisActionPerformed
        primeiroNum = Double.parseDouble(jTxtDisplay.getText());
        jTxtDisplay.setText(null);
        operacoes=("+");
    }//GEN-LAST:event_jbtnMaisActionPerformed

    private void jbtnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDividirActionPerformed
        primeiroNum = Double.parseDouble(jTxtDisplay.getText());
        jTxtDisplay.setText(null);
        operacoes=("÷");
    }//GEN-LAST:event_jbtnDividirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora_C.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora_C.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora_C.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora_C.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora_C().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton29;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jTxtDisplay;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnBackspace;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnCos;
    private javax.swing.JButton jbtnDividir;
    private javax.swing.JButton jbtnEuler;
    private javax.swing.JButton jbtnLog;
    private javax.swing.JButton jbtnMais;
    private javax.swing.JButton jbtnMaisMenos;
    private javax.swing.JButton jbtnMenos;
    private javax.swing.JButton jbtnPi;
    private javax.swing.JButton jbtnPonto;
    private javax.swing.JButton jbtnRaiz;
    private javax.swing.JButton jbtnSen;
    private javax.swing.JButton jbtnTan;
    private javax.swing.JButton jbtnVezes;
    private javax.swing.JButton jbtnX2;
    private javax.swing.JButton jbtnX3;
    private javax.swing.JButton jbtnXY;
    private javax.swing.JButton jbtnresultado;
    // End of variables declaration//GEN-END:variables
}
